# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: json_reflection.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'json_reflection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15json_reflection.proto\x12\x0fjson_reflection\"&\n\x10JsonFieldRequest\x12\x12\n\nfield_path\x18\x01 \x01(\t\"\"\n\x11JsonFieldResponse\x12\r\n\x05value\x18\x01 \x01(\t\"\x1b\n\tFieldList\x12\x0e\n\x06\x66ields\x18\x01 \x03(\t\":\n\x11\x46ieldModification\x12\x12\n\nfield_path\x18\x01 \x01(\t\x12\x11\n\tnew_value\x18\x02 \x01(\t\"3\n\x0fOperationStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\x8b\x02\n\x15JsonReflectionService\x12W\n\x0cGetJsonField\x12!.json_reflection.JsonFieldRequest\x1a\".json_reflection.JsonFieldResponse\"\x00\x12\x42\n\nListFields\x12\x16.json_reflection.Empty\x1a\x1a.json_reflection.FieldList\"\x00\x12U\n\x0bModifyField\x12\".json_reflection.FieldModification\x1a .json_reflection.OperationStatus\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'json_reflection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JSONFIELDREQUEST']._serialized_start=42
  _globals['_JSONFIELDREQUEST']._serialized_end=80
  _globals['_JSONFIELDRESPONSE']._serialized_start=82
  _globals['_JSONFIELDRESPONSE']._serialized_end=116
  _globals['_FIELDLIST']._serialized_start=118
  _globals['_FIELDLIST']._serialized_end=145
  _globals['_FIELDMODIFICATION']._serialized_start=147
  _globals['_FIELDMODIFICATION']._serialized_end=205
  _globals['_OPERATIONSTATUS']._serialized_start=207
  _globals['_OPERATIONSTATUS']._serialized_end=258
  _globals['_EMPTY']._serialized_start=260
  _globals['_EMPTY']._serialized_end=267
  _globals['_JSONREFLECTIONSERVICE']._serialized_start=270
  _globals['_JSONREFLECTIONSERVICE']._serialized_end=537
# @@protoc_insertion_point(module_scope)
