# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import json_reflection_pb2 as json__reflection__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in json_reflection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JsonReflectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJsonField = channel.unary_unary(
                '/json_reflection.JsonReflectionService/GetJsonField',
                request_serializer=json__reflection__pb2.JsonFieldRequest.SerializeToString,
                response_deserializer=json__reflection__pb2.JsonFieldResponse.FromString,
                _registered_method=True)
        self.ListFields = channel.unary_unary(
                '/json_reflection.JsonReflectionService/ListFields',
                request_serializer=json__reflection__pb2.Empty.SerializeToString,
                response_deserializer=json__reflection__pb2.FieldList.FromString,
                _registered_method=True)
        self.ModifyField = channel.unary_unary(
                '/json_reflection.JsonReflectionService/ModifyField',
                request_serializer=json__reflection__pb2.FieldModification.SerializeToString,
                response_deserializer=json__reflection__pb2.OperationStatus.FromString,
                _registered_method=True)


class JsonReflectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetJsonField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFields(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyField(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JsonReflectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJsonField': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJsonField,
                    request_deserializer=json__reflection__pb2.JsonFieldRequest.FromString,
                    response_serializer=json__reflection__pb2.JsonFieldResponse.SerializeToString,
            ),
            'ListFields': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFields,
                    request_deserializer=json__reflection__pb2.Empty.FromString,
                    response_serializer=json__reflection__pb2.FieldList.SerializeToString,
            ),
            'ModifyField': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyField,
                    request_deserializer=json__reflection__pb2.FieldModification.FromString,
                    response_serializer=json__reflection__pb2.OperationStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'json_reflection.JsonReflectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('json_reflection.JsonReflectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JsonReflectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetJsonField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/json_reflection.JsonReflectionService/GetJsonField',
            json__reflection__pb2.JsonFieldRequest.SerializeToString,
            json__reflection__pb2.JsonFieldResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/json_reflection.JsonReflectionService/ListFields',
            json__reflection__pb2.Empty.SerializeToString,
            json__reflection__pb2.FieldList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyField(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/json_reflection.JsonReflectionService/ModifyField',
            json__reflection__pb2.FieldModification.SerializeToString,
            json__reflection__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
