// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: json_reflection.proto

#include "json_reflection.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace json_reflection {
PROTOBUF_CONSTEXPR JsonFieldRequest::JsonFieldRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.field_path_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct JsonFieldRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JsonFieldRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~JsonFieldRequestDefaultTypeInternal() {}
  union {
    JsonFieldRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JsonFieldRequestDefaultTypeInternal _JsonFieldRequest_default_instance_;
PROTOBUF_CONSTEXPR JsonFieldResponse::JsonFieldResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.value_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct JsonFieldResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JsonFieldResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~JsonFieldResponseDefaultTypeInternal() {}
  union {
    JsonFieldResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JsonFieldResponseDefaultTypeInternal _JsonFieldResponse_default_instance_;
PROTOBUF_CONSTEXPR FieldList::FieldList(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.fields_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FieldListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FieldListDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FieldListDefaultTypeInternal() {}
  union {
    FieldList _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FieldListDefaultTypeInternal _FieldList_default_instance_;
PROTOBUF_CONSTEXPR FieldModification::FieldModification(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.field_path_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.new_value_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FieldModificationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FieldModificationDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FieldModificationDefaultTypeInternal() {}
  union {
    FieldModification _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FieldModificationDefaultTypeInternal _FieldModification_default_instance_;
PROTOBUF_CONSTEXPR OperationStatus::OperationStatus(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct OperationStatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR OperationStatusDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~OperationStatusDefaultTypeInternal() {}
  union {
    OperationStatus _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 OperationStatusDefaultTypeInternal _OperationStatus_default_instance_;
PROTOBUF_CONSTEXPR Empty::Empty(
    ::_pbi::ConstantInitialized) {}
struct EmptyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyDefaultTypeInternal() {}
  union {
    Empty _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyDefaultTypeInternal _Empty_default_instance_;
}  // namespace json_reflection
static ::_pb::Metadata file_level_metadata_json_5freflection_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_json_5freflection_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_json_5freflection_2eproto = nullptr;

const uint32_t TableStruct_json_5freflection_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::json_reflection::JsonFieldRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::json_reflection::JsonFieldRequest, _impl_.field_path_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::json_reflection::JsonFieldResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::json_reflection::JsonFieldResponse, _impl_.value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::json_reflection::FieldList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::json_reflection::FieldList, _impl_.fields_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::json_reflection::FieldModification, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::json_reflection::FieldModification, _impl_.field_path_),
  PROTOBUF_FIELD_OFFSET(::json_reflection::FieldModification, _impl_.new_value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::json_reflection::OperationStatus, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::json_reflection::OperationStatus, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::json_reflection::OperationStatus, _impl_.message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::json_reflection::Empty, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::json_reflection::JsonFieldRequest)},
  { 7, -1, -1, sizeof(::json_reflection::JsonFieldResponse)},
  { 14, -1, -1, sizeof(::json_reflection::FieldList)},
  { 21, -1, -1, sizeof(::json_reflection::FieldModification)},
  { 29, -1, -1, sizeof(::json_reflection::OperationStatus)},
  { 37, -1, -1, sizeof(::json_reflection::Empty)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::json_reflection::_JsonFieldRequest_default_instance_._instance,
  &::json_reflection::_JsonFieldResponse_default_instance_._instance,
  &::json_reflection::_FieldList_default_instance_._instance,
  &::json_reflection::_FieldModification_default_instance_._instance,
  &::json_reflection::_OperationStatus_default_instance_._instance,
  &::json_reflection::_Empty_default_instance_._instance,
};

const char descriptor_table_protodef_json_5freflection_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025json_reflection.proto\022\017json_reflection"
  "\"&\n\020JsonFieldRequest\022\022\n\nfield_path\030\001 \001(\t"
  "\"\"\n\021JsonFieldResponse\022\r\n\005value\030\001 \001(\t\"\033\n\t"
  "FieldList\022\016\n\006fields\030\001 \003(\t\":\n\021FieldModifi"
  "cation\022\022\n\nfield_path\030\001 \001(\t\022\021\n\tnew_value\030"
  "\002 \001(\t\"3\n\017OperationStatus\022\017\n\007success\030\001 \001("
  "\010\022\017\n\007message\030\002 \001(\t\"\007\n\005Empty2\213\002\n\025JsonRefl"
  "ectionService\022W\n\014GetJsonField\022!.json_ref"
  "lection.JsonFieldRequest\032\".json_reflecti"
  "on.JsonFieldResponse\"\000\022B\n\nListFields\022\026.j"
  "son_reflection.Empty\032\032.json_reflection.F"
  "ieldList\"\000\022U\n\013ModifyField\022\".json_reflect"
  "ion.FieldModification\032 .json_reflection."
  "OperationStatus\"\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_json_5freflection_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_json_5freflection_2eproto = {
    false, false, 545, descriptor_table_protodef_json_5freflection_2eproto,
    "json_reflection.proto",
    &descriptor_table_json_5freflection_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_json_5freflection_2eproto::offsets,
    file_level_metadata_json_5freflection_2eproto, file_level_enum_descriptors_json_5freflection_2eproto,
    file_level_service_descriptors_json_5freflection_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_json_5freflection_2eproto_getter() {
  return &descriptor_table_json_5freflection_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_json_5freflection_2eproto(&descriptor_table_json_5freflection_2eproto);
namespace json_reflection {

// ===================================================================

class JsonFieldRequest::_Internal {
 public:
};

JsonFieldRequest::JsonFieldRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:json_reflection.JsonFieldRequest)
}
JsonFieldRequest::JsonFieldRequest(const JsonFieldRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  JsonFieldRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.field_path_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.field_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.field_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_field_path().empty()) {
    _this->_impl_.field_path_.Set(from._internal_field_path(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:json_reflection.JsonFieldRequest)
}

inline void JsonFieldRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.field_path_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.field_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.field_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

JsonFieldRequest::~JsonFieldRequest() {
  // @@protoc_insertion_point(destructor:json_reflection.JsonFieldRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void JsonFieldRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.field_path_.Destroy();
}

void JsonFieldRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void JsonFieldRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:json_reflection.JsonFieldRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.field_path_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* JsonFieldRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string field_path = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_field_path();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "json_reflection.JsonFieldRequest.field_path"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* JsonFieldRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:json_reflection.JsonFieldRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string field_path = 1;
  if (!this->_internal_field_path().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_field_path().data(), static_cast<int>(this->_internal_field_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "json_reflection.JsonFieldRequest.field_path");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_field_path(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:json_reflection.JsonFieldRequest)
  return target;
}

size_t JsonFieldRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:json_reflection.JsonFieldRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string field_path = 1;
  if (!this->_internal_field_path().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_field_path());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData JsonFieldRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    JsonFieldRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*JsonFieldRequest::GetClassData() const { return &_class_data_; }


void JsonFieldRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<JsonFieldRequest*>(&to_msg);
  auto& from = static_cast<const JsonFieldRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:json_reflection.JsonFieldRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_field_path().empty()) {
    _this->_internal_set_field_path(from._internal_field_path());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void JsonFieldRequest::CopyFrom(const JsonFieldRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:json_reflection.JsonFieldRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JsonFieldRequest::IsInitialized() const {
  return true;
}

void JsonFieldRequest::InternalSwap(JsonFieldRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.field_path_, lhs_arena,
      &other->_impl_.field_path_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata JsonFieldRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_json_5freflection_2eproto_getter, &descriptor_table_json_5freflection_2eproto_once,
      file_level_metadata_json_5freflection_2eproto[0]);
}

// ===================================================================

class JsonFieldResponse::_Internal {
 public:
};

JsonFieldResponse::JsonFieldResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:json_reflection.JsonFieldResponse)
}
JsonFieldResponse::JsonFieldResponse(const JsonFieldResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  JsonFieldResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_value().empty()) {
    _this->_impl_.value_.Set(from._internal_value(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:json_reflection.JsonFieldResponse)
}

inline void JsonFieldResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

JsonFieldResponse::~JsonFieldResponse() {
  // @@protoc_insertion_point(destructor:json_reflection.JsonFieldResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void JsonFieldResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.value_.Destroy();
}

void JsonFieldResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void JsonFieldResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:json_reflection.JsonFieldResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* JsonFieldResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_value();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "json_reflection.JsonFieldResponse.value"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* JsonFieldResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:json_reflection.JsonFieldResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string value = 1;
  if (!this->_internal_value().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_value().data(), static_cast<int>(this->_internal_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "json_reflection.JsonFieldResponse.value");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:json_reflection.JsonFieldResponse)
  return target;
}

size_t JsonFieldResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:json_reflection.JsonFieldResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string value = 1;
  if (!this->_internal_value().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData JsonFieldResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    JsonFieldResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*JsonFieldResponse::GetClassData() const { return &_class_data_; }


void JsonFieldResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<JsonFieldResponse*>(&to_msg);
  auto& from = static_cast<const JsonFieldResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:json_reflection.JsonFieldResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void JsonFieldResponse::CopyFrom(const JsonFieldResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:json_reflection.JsonFieldResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JsonFieldResponse::IsInitialized() const {
  return true;
}

void JsonFieldResponse::InternalSwap(JsonFieldResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.value_, lhs_arena,
      &other->_impl_.value_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata JsonFieldResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_json_5freflection_2eproto_getter, &descriptor_table_json_5freflection_2eproto_once,
      file_level_metadata_json_5freflection_2eproto[1]);
}

// ===================================================================

class FieldList::_Internal {
 public:
};

FieldList::FieldList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:json_reflection.FieldList)
}
FieldList::FieldList(const FieldList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FieldList* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.fields_){from._impl_.fields_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:json_reflection.FieldList)
}

inline void FieldList::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.fields_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

FieldList::~FieldList() {
  // @@protoc_insertion_point(destructor:json_reflection.FieldList)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FieldList::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.fields_.~RepeatedPtrField();
}

void FieldList::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FieldList::Clear() {
// @@protoc_insertion_point(message_clear_start:json_reflection.FieldList)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.fields_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FieldList::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string fields = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_fields();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "json_reflection.FieldList.fields"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FieldList::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:json_reflection.FieldList)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string fields = 1;
  for (int i = 0, n = this->_internal_fields_size(); i < n; i++) {
    const auto& s = this->_internal_fields(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "json_reflection.FieldList.fields");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:json_reflection.FieldList)
  return target;
}

size_t FieldList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:json_reflection.FieldList)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string fields = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.fields_.size());
  for (int i = 0, n = _impl_.fields_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.fields_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FieldList::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FieldList::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FieldList::GetClassData() const { return &_class_data_; }


void FieldList::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FieldList*>(&to_msg);
  auto& from = static_cast<const FieldList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:json_reflection.FieldList)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.fields_.MergeFrom(from._impl_.fields_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FieldList::CopyFrom(const FieldList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:json_reflection.FieldList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FieldList::IsInitialized() const {
  return true;
}

void FieldList::InternalSwap(FieldList* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.fields_.InternalSwap(&other->_impl_.fields_);
}

::PROTOBUF_NAMESPACE_ID::Metadata FieldList::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_json_5freflection_2eproto_getter, &descriptor_table_json_5freflection_2eproto_once,
      file_level_metadata_json_5freflection_2eproto[2]);
}

// ===================================================================

class FieldModification::_Internal {
 public:
};

FieldModification::FieldModification(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:json_reflection.FieldModification)
}
FieldModification::FieldModification(const FieldModification& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FieldModification* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.field_path_){}
    , decltype(_impl_.new_value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.field_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.field_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_field_path().empty()) {
    _this->_impl_.field_path_.Set(from._internal_field_path(), 
      _this->GetArenaForAllocation());
  }
  _impl_.new_value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.new_value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_new_value().empty()) {
    _this->_impl_.new_value_.Set(from._internal_new_value(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:json_reflection.FieldModification)
}

inline void FieldModification::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.field_path_){}
    , decltype(_impl_.new_value_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.field_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.field_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.new_value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.new_value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FieldModification::~FieldModification() {
  // @@protoc_insertion_point(destructor:json_reflection.FieldModification)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FieldModification::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.field_path_.Destroy();
  _impl_.new_value_.Destroy();
}

void FieldModification::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FieldModification::Clear() {
// @@protoc_insertion_point(message_clear_start:json_reflection.FieldModification)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.field_path_.ClearToEmpty();
  _impl_.new_value_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FieldModification::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string field_path = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_field_path();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "json_reflection.FieldModification.field_path"));
        } else
          goto handle_unusual;
        continue;
      // string new_value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_new_value();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "json_reflection.FieldModification.new_value"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FieldModification::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:json_reflection.FieldModification)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string field_path = 1;
  if (!this->_internal_field_path().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_field_path().data(), static_cast<int>(this->_internal_field_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "json_reflection.FieldModification.field_path");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_field_path(), target);
  }

  // string new_value = 2;
  if (!this->_internal_new_value().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_new_value().data(), static_cast<int>(this->_internal_new_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "json_reflection.FieldModification.new_value");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_new_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:json_reflection.FieldModification)
  return target;
}

size_t FieldModification::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:json_reflection.FieldModification)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string field_path = 1;
  if (!this->_internal_field_path().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_field_path());
  }

  // string new_value = 2;
  if (!this->_internal_new_value().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_new_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FieldModification::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FieldModification::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FieldModification::GetClassData() const { return &_class_data_; }


void FieldModification::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FieldModification*>(&to_msg);
  auto& from = static_cast<const FieldModification&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:json_reflection.FieldModification)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_field_path().empty()) {
    _this->_internal_set_field_path(from._internal_field_path());
  }
  if (!from._internal_new_value().empty()) {
    _this->_internal_set_new_value(from._internal_new_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FieldModification::CopyFrom(const FieldModification& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:json_reflection.FieldModification)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FieldModification::IsInitialized() const {
  return true;
}

void FieldModification::InternalSwap(FieldModification* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.field_path_, lhs_arena,
      &other->_impl_.field_path_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.new_value_, lhs_arena,
      &other->_impl_.new_value_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata FieldModification::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_json_5freflection_2eproto_getter, &descriptor_table_json_5freflection_2eproto_once,
      file_level_metadata_json_5freflection_2eproto[3]);
}

// ===================================================================

class OperationStatus::_Internal {
 public:
};

OperationStatus::OperationStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:json_reflection.OperationStatus)
}
OperationStatus::OperationStatus(const OperationStatus& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  OperationStatus* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.success_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.success_ = from._impl_.success_;
  // @@protoc_insertion_point(copy_constructor:json_reflection.OperationStatus)
}

inline void OperationStatus::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.success_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

OperationStatus::~OperationStatus() {
  // @@protoc_insertion_point(destructor:json_reflection.OperationStatus)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void OperationStatus::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
}

void OperationStatus::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void OperationStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:json_reflection.OperationStatus)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* OperationStatus::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "json_reflection.OperationStatus.message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* OperationStatus::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:json_reflection.OperationStatus)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "json_reflection.OperationStatus.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:json_reflection.OperationStatus)
  return target;
}

size_t OperationStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:json_reflection.OperationStatus)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData OperationStatus::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    OperationStatus::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*OperationStatus::GetClassData() const { return &_class_data_; }


void OperationStatus::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<OperationStatus*>(&to_msg);
  auto& from = static_cast<const OperationStatus&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:json_reflection.OperationStatus)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void OperationStatus::CopyFrom(const OperationStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:json_reflection.OperationStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OperationStatus::IsInitialized() const {
  return true;
}

void OperationStatus::InternalSwap(OperationStatus* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  swap(_impl_.success_, other->_impl_.success_);
}

::PROTOBUF_NAMESPACE_ID::Metadata OperationStatus::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_json_5freflection_2eproto_getter, &descriptor_table_json_5freflection_2eproto_once,
      file_level_metadata_json_5freflection_2eproto[4]);
}

// ===================================================================

class Empty::_Internal {
 public:
};

Empty::Empty(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:json_reflection.Empty)
}
Empty::Empty(const Empty& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  Empty* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:json_reflection.Empty)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Empty::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Empty::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Empty::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_json_5freflection_2eproto_getter, &descriptor_table_json_5freflection_2eproto_once,
      file_level_metadata_json_5freflection_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace json_reflection
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::json_reflection::JsonFieldRequest*
Arena::CreateMaybeMessage< ::json_reflection::JsonFieldRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::json_reflection::JsonFieldRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::json_reflection::JsonFieldResponse*
Arena::CreateMaybeMessage< ::json_reflection::JsonFieldResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::json_reflection::JsonFieldResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::json_reflection::FieldList*
Arena::CreateMaybeMessage< ::json_reflection::FieldList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::json_reflection::FieldList >(arena);
}
template<> PROTOBUF_NOINLINE ::json_reflection::FieldModification*
Arena::CreateMaybeMessage< ::json_reflection::FieldModification >(Arena* arena) {
  return Arena::CreateMessageInternal< ::json_reflection::FieldModification >(arena);
}
template<> PROTOBUF_NOINLINE ::json_reflection::OperationStatus*
Arena::CreateMaybeMessage< ::json_reflection::OperationStatus >(Arena* arena) {
  return Arena::CreateMessageInternal< ::json_reflection::OperationStatus >(arena);
}
template<> PROTOBUF_NOINLINE ::json_reflection::Empty*
Arena::CreateMaybeMessage< ::json_reflection::Empty >(Arena* arena) {
  return Arena::CreateMessageInternal< ::json_reflection::Empty >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
